version: '3.9'
services:
  server:
    build: ./server
    container_name: myserver_c
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: myclient_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true